name: Primitive UI 스토리북 배포
run-name: ${{ github.actor }}의 Primitive UI 스토리북 배포
on:
  pull_request:
    branches:
      - develop
    paths:
      - "packages/primitive/components/**/*"

permissions:
  contents: read
  pull-requests: write

jobs:
  set-up:
    uses: ghdtjgus76/warrr-ui/.github/workflows/set-up.yml@develop
  storybook:
    runs-on: ubuntu-latest
    needs: set-up
    steps:
      - name: Check if token exists
        run: |
          if [ -n "${{ secrets.PRIMITIVE_UI_CHROMATIC_TOKEN }}" ]; then
            echo "PRIMITIVE_UI_CHROMATIC_TOKEN is set"
          else
            echo "PRIMITIVE_UI_CHROMATIC_TOKEN is not set"
          fi

      - name: chromatic에 배포
        id: publish_chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.PRIMITIVE_UI_CHROMATIC_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          workingDir: packages/primitive

      - name: chromatic 배포 URL 댓글 작성
        uses: thollander/actions-comment-pull-request@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: "🐱 스토리북이 배포되었습니다: ${{ steps.publish_chromatic.outputs.url }} 🐱"
