name: 설정 및 의존성 설치

on: workflow_call

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: 레포지토리 체크아웃
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Node.js 설정
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: pnpm 8.15.6 설치
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.6

      - name: 캐시 의존성
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: 의존성 설치
        run: pnpm install --frozen-lockfile

      - name: 의존성 아티팩트로 저장
        uses: actions/upload-artifact@v3
        with:
          name: pnpm-dependencies
          path: |
            node_modules
            ~/.pnpm-store
